# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

search_trigger: false
# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ";?"
    replace: "¿"
  - trigger: ";;o"
    replace: "Octavio"
  - trigger: ";;s"
    replace: "Sardi"
  - trigger: ";;f"
    replace: "Octavio Sardi"
  - trigger: ";l"
    replace: "76199"
  - trigger: ";d"
    replace: "41542861"
  - trigger: ";n"
    replace: "ñ"
  - trigger: ";N"
    replace: "Ñ"
  - trigger: ";a"
    replace: "á"
  - trigger: ";A"
    replace: "Á"
  - trigger: ";e"
    replace: "é"
  - trigger: ";E"
    replace: "É"
  - trigger: ";i"
    replace: "í"
  - trigger: ";I"
    replace: "Í"
  - trigger: ";o"
    replace: "ó"
  - trigger: ";O"
    replace: "Ó"
  - trigger: ";u"
    replace: "ú"
  - trigger: ";U"
    replace: "Ú"
  - trigger: ";github"
    replace: "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"
  - trigger: "//JO"
    replace: "//Just Octavio's"
  - trigger: "aprticularmente"
    replace: "particularmente"
  - trigger: "Aprticularmente"
    replace: "Particularmente"
  - trigger: "apra"
    replace: "para"
  - trigger: "Apra"
    replace: "Para"
  - trigger: "uqe"
    replace: "que"
  - trigger: ";pmail"
    replace: "octavio.sardi@proton.me"
  - trigger: ";gmail"
    replace: "octasardi98@gmail.com"
  - trigger: ";hmail"
    replace: "octaviosardi@hotmail.com"
  - trigger: ";fmail"
    replace: "76199@sistemas.frc.utn.edu.ar"
  
  # Dates
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%m-%Y"

  # Shell commands
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Obsidian URI
  - trigger: ";m"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
